#Preparamos un OS liviano para los proyectos, alpine es la opcion
FROM alpine:latest 
#Instalamos apache
RUN apk add apache2 apache2-utils apache2-ssl apache2-proxy
#Instalamos php
RUN apk add php php-pdo php-pdo_mysql php-pdo_sqlite php-sqlite3 php-mysqli php-mysqlnd php-apache2 php-session php-openssl php-iconv php-mbstring php-intl php-exif php-json php-curl php-zip php-xml php-xmlwriter php-xmlreader php-phar php-cli php-common php-tokenizer php-ctype php-dom php-fileinfo
#icu-libs mariadb-conector-c libxml2 sqlite-libs libjpeg-turbo
#Preparamos el composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN rm composer-setup.php
#Instalamos el composer
RUN composer global require laravel/installer
#Ejecutamos apache
CMD ["httpd", "-D", "FOREGROUND"]